stages:
    - build
    - test
    - deploy

build_job:
    stage: build
    script:
        - docker --version
        - sudo docker build -t pyapp .
    tags:
        - python 
        - server
        - shell

deployment_job:
    stage: deploy
    script:
        - sudo docker stop pythoncontainer21 && sudo docker rm pythoncontainer21
        - sudo docker run -d --name pythoncontainer21 -p 3000:8080 pyapp
        - sudo docker login  -u  $DOCKER_USERNAME -p $DOCKER_USER_TOKEN
        - sudo docker tag pyapp $DOCKER_USERNAME/pyapp21
        - sudo docker push $DOCKER_USERNAME/pyapp21
    tags:
        - python 
        - server
        - shell